name: run-tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v1
    - name: setup julia env
      uses: julia-actions/setup-julia@v1.0.1
      with:
        version: 1
    - name: run tests
      run: make test
