name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: setup env
      uses: julia-actions/setup-julia@v1.0.1
    - name: run tests
      run: |
        make test
